# Generated by Django 2.1.5 on 2020-11-10 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity_id', models.CharField(max_length=10)),
                ('commodity_price', models.CharField(max_length=10)),
                ('commodity_name', models.CharField(max_length=10)),
                ('commodity_contends', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CommodityToshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(max_length=8)),
                ('commodity_id', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10)),
                ('commodity_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_id', models.CharField(max_length=10)),
                ('pay_time', models.CharField(max_length=10)),
                ('pay_money', models.CharField(max_length=10)),
                ('order_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PosInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField()),
                ('start_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=32, null=True)),
                ('shop_owner', models.CharField(max_length=32, null=True)),
                ('shop_ownerID', models.CharField(max_length=18)),
                ('shop_position', models.CharField(max_length=32, null=True)),
                ('phone_number', models.CharField(max_length=11, null=True)),
                ('contends', models.TextField()),
                ('create_time', models.DateTimeField()),
                ('last_update', models.DateTimeField()),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='posinfo',
            name='shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Shop'),
        ),
    ]
