# Generated by Django 2.2 on 2020-12-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201205_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='pay_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
