# Generated by Django 2.2 on 2020-12-05 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20201205_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='commodity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Commodity'),
        ),
    ]
