# Generated by Django 2.2 on 2020-12-05 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20201205_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='pay_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
