# Generated by Django 2.2 on 2020-12-07 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20201207_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commoditytoshop',
            old_name='shop_id',
            new_name='shop_owner',
        ),
    ]
