# Generated by Django 2.2 on 2020-12-08 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20201207_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AddField(
            model_name='commodity',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.Shop'),
        ),
        migrations.AddField(
            model_name='pay',
            name='pay_No',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='pay',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.Shop'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='commodity_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pay',
            name='POS',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.PosInfo'),
        ),
        migrations.AlterField(
            model_name='pay',
            name='pay_money',
            field=models.IntegerField(default=0),
        ),
    ]
