# Generated by Django 2.2 on 2020-12-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20201208_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_id',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
