# Generated by Django 2.2 on 2020-12-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_auto_20201209_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='commodity_contends',
            field=models.TextField(null=True),
        ),
    ]
