# Generated by Django 2.2 on 2020-12-03 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_shopowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='IDnumber',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
