# Generated by Django 2.2 on 2020-12-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201203_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='IDnumber',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
