# Generated by Django 2.2 on 2020-12-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201203_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='sex',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='IDnumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
