# Generated by Django 2.2 on 2020-12-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20201203_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopowner',
            name='owner_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='real_name',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
