# Generated by Django 2.2 on 2020-12-05 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201203_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='IDnumber',
        ),
    ]
