# Generated by Django 2.1.5 on 2020-12-07 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20201205_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='dept',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.Institute'),
        ),
    ]
